### ISSUE TITLE
Sections using Base.Grisu need to be rewritten

### ISSUE THREAD

**Issue by dmbates** [JuliaGraphics/Showoff.jl#24]
As of https://github.com/JuliaLang/julia/pull/32859 `Base.Grisu` has been removed from Julia and the sections of `Showoff` that depend on Grisu will need to be rewritten, I believe.

**Comment by dmbates** [comment]
Actually, I see from the News file changes that Grisu was replaced by Ryu in version 1.4
```
The `Base.Grisu` code has been officially removed (float printing was switched to the ryu algorithm code in 1.4)
```

**Comment by quinnj** [comment]
Luckily, it looks like a lot of the code can be simplified with the new `Printf.format(::Printf.format, args...)` functionality. It allows avoiding the `@sprintf` macro usage and dynamically formatting things much easier.

**Comment by jw3126** [comment]
@quinnj can `Printf` also help with the following:
https://github.com/JuliaGraphics/Showoff.jl/blob/f5e532948b05ee6e86e35e91fc745969d0304bf1/test/runtests.jl#L47

**Comment by quinnj** [comment]
What are you hoping `Printf` can do for you there? (sorry, I'm not familiar w/ showoff at all)

**Comment by jw3126** [comment]
Something like this:
```julia
function showoff(x)
    # trivial code
    intermediate = Printf.nontrivial(...)
    # trivial code
end
@test showoff(1e-39) == "1×10³⁹"
```
For instance if `nontrivial` could decompose `1.234e-39::Float64` into e.g. `(mantissa=[1,2,3,4], exponent=-39, sign=:+)` that would be great.

**Comment by quinnj** [comment]
Not that I can tell; it's really just for printing things to a buffer and it's pretty highly optimized for that, so it doesn't really do any decomposing.

**Comment by jw3126** [comment]
So one way or another we need to pass from `1.234e-39` to the decimal representation of the mantissa and the exponent. AFAICT `Grisu.grisu` was the non trivial piece in doing this and now I am sure, what it should be replaced by?

**Comment by KristofferC** [comment]
> Grisu.grisu was the non trivial piece in doing this and now I am sure, what it should be replaced by?

Copy paste whatever you need from Grisu into here?

**Comment by KristofferC** [comment]
See https://github.com/JuliaAttic/Grisu.jl and https://github.com/JuliaGraphics/Showoff.jl/pull/25.

**Comment by jw3126** [comment]
Thanks @KristofferC !
