### ISSUE TITLE
takebuf_string deprecation in v0.6

### ISSUE THREAD

**Issue by dmbates** [JuliaGraphics/Showoff.jl#3]
In v0.6  `takebuf_string` (line 44 of `Showoff.jl`) is deprecated.  It can be replaced with `String(Compat.take!(buf))` in v0.5 and v0.6 but I don't know about v0.4.  Is it still necessary to support v0.4?

**Comment by dmbates** [comment]
See #4

**Comment by tlnagy** [comment]
This is closed by #4
