### ISSUE TITLE
Sever fork link from dcjones/Showoff?

### ISSUE THREAD

**Issue by ararslan** [JuliaGraphics/Showoff.jl#7]
If there is no intention of resubmitting the changes here back to dcjones/Showoff.jl, I recommend that we sever the fork link. This allows searching code and is overall just cleaner for continued development. We already have METADATA pointing to this repository anyway, which suggests to me that changes won't be upstreamed.

If folks think this is a good idea, I can contact GitHub to have them remove the link.

**Comment by ararslan** [comment]
cc @tlnagy

**Comment by tlnagy** [comment]
Yeah, I think that's a good idea. Thanks!

**Comment by tlnagy** [comment]
We should credit Daniel for the original work in the README though

**Comment by ararslan** [comment]
Definitely.

**Comment by ararslan** [comment]
Done
